/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as HubHubIdRouteImport } from "./routes/hub/$hubId";
import { Route as DeploymentDeploymentIdRouteRouteImport } from "./routes/deployment/$deploymentId/route";
import { Route as DeploymentDeploymentIdIndexRouteImport } from "./routes/deployment/$deploymentId/index";
import { Route as DeploymentDeploymentIdEditRouteImport } from "./routes/deployment/$deploymentId/edit";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const HubHubIdRoute = HubHubIdRouteImport.update({
  id: "/hub/$hubId",
  path: "/hub/$hubId",
  getParentRoute: () => rootRouteImport,
} as any);
const DeploymentDeploymentIdRouteRoute =
  DeploymentDeploymentIdRouteRouteImport.update({
    id: "/deployment/$deploymentId",
    path: "/deployment/$deploymentId",
    getParentRoute: () => rootRouteImport,
  } as any);
const DeploymentDeploymentIdIndexRoute =
  DeploymentDeploymentIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DeploymentDeploymentIdRouteRoute,
  } as any);
const DeploymentDeploymentIdEditRoute =
  DeploymentDeploymentIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => DeploymentDeploymentIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/deployment/$deploymentId": typeof DeploymentDeploymentIdRouteRouteWithChildren;
  "/hub/$hubId": typeof HubHubIdRoute;
  "/deployment/$deploymentId/edit": typeof DeploymentDeploymentIdEditRoute;
  "/deployment/$deploymentId/": typeof DeploymentDeploymentIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/hub/$hubId": typeof HubHubIdRoute;
  "/deployment/$deploymentId/edit": typeof DeploymentDeploymentIdEditRoute;
  "/deployment/$deploymentId": typeof DeploymentDeploymentIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/deployment/$deploymentId": typeof DeploymentDeploymentIdRouteRouteWithChildren;
  "/hub/$hubId": typeof HubHubIdRoute;
  "/deployment/$deploymentId/edit": typeof DeploymentDeploymentIdEditRoute;
  "/deployment/$deploymentId/": typeof DeploymentDeploymentIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/deployment/$deploymentId"
    | "/hub/$hubId"
    | "/deployment/$deploymentId/edit"
    | "/deployment/$deploymentId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/hub/$hubId"
    | "/deployment/$deploymentId/edit"
    | "/deployment/$deploymentId";
  id:
    | "__root__"
    | "/"
    | "/deployment/$deploymentId"
    | "/hub/$hubId"
    | "/deployment/$deploymentId/edit"
    | "/deployment/$deploymentId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DeploymentDeploymentIdRouteRoute: typeof DeploymentDeploymentIdRouteRouteWithChildren;
  HubHubIdRoute: typeof HubHubIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/hub/$hubId": {
      id: "/hub/$hubId";
      path: "/hub/$hubId";
      fullPath: "/hub/$hubId";
      preLoaderRoute: typeof HubHubIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deployment/$deploymentId": {
      id: "/deployment/$deploymentId";
      path: "/deployment/$deploymentId";
      fullPath: "/deployment/$deploymentId";
      preLoaderRoute: typeof DeploymentDeploymentIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deployment/$deploymentId/": {
      id: "/deployment/$deploymentId/";
      path: "/";
      fullPath: "/deployment/$deploymentId/";
      preLoaderRoute: typeof DeploymentDeploymentIdIndexRouteImport;
      parentRoute: typeof DeploymentDeploymentIdRouteRoute;
    };
    "/deployment/$deploymentId/edit": {
      id: "/deployment/$deploymentId/edit";
      path: "/edit";
      fullPath: "/deployment/$deploymentId/edit";
      preLoaderRoute: typeof DeploymentDeploymentIdEditRouteImport;
      parentRoute: typeof DeploymentDeploymentIdRouteRoute;
    };
  }
}

interface DeploymentDeploymentIdRouteRouteChildren {
  DeploymentDeploymentIdEditRoute: typeof DeploymentDeploymentIdEditRoute;
  DeploymentDeploymentIdIndexRoute: typeof DeploymentDeploymentIdIndexRoute;
}

const DeploymentDeploymentIdRouteRouteChildren: DeploymentDeploymentIdRouteRouteChildren =
  {
    DeploymentDeploymentIdEditRoute: DeploymentDeploymentIdEditRoute,
    DeploymentDeploymentIdIndexRoute: DeploymentDeploymentIdIndexRoute,
  };

const DeploymentDeploymentIdRouteRouteWithChildren =
  DeploymentDeploymentIdRouteRoute._addFileChildren(
    DeploymentDeploymentIdRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeploymentDeploymentIdRouteRoute:
    DeploymentDeploymentIdRouteRouteWithChildren,
  HubHubIdRoute: HubHubIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
